// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type default as NamesTable } from './Names';
import { type default as ProjectsTable } from './Projects';

export default interface PublicSchema {
  names: NamesTable;

  projects: ProjectsTable;
}
