// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type default as NamesTable } from './Names';

export default interface PublicSchema {
  names: NamesTable;
}
